basePath: /
definitions:
  models.ApiResponse:
    properties:
      data:
        description: Optional, for successful responses
      error:
        description: Optional, for error details
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation for GoScraper.
  title: GoScraper API
  version: "1.0"
paths:
  /:
    get:
      description: Returns a welcome message
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiResponse'
      summary: Get the home message
      tags:
      - Home
swagger: "2.0"
